---
env:
  browser: true
  es2021: true
extends:
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - jsx-a11y
  - react
  - react-hooks
rules:
  react-hooks/exhaustive-deps: warn
  react-hooks/rules-of-hooks: error
  react/jsx-uses-react: 'off'
  react/prop-types: 0
  react/react-in-jsx-scope: 'off'
  import/no-cycle: off
settings:
  react:
    version: detect
