---
release:
  plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/npm'
    - npmPublish: true
  - '@semantic-release/github'
  prepare:
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - path: '@semantic-release/git'
    assets:
    - package.json
    - yarn-lock.json
    - CHANGELOG.md
    message: 'release: ${nextRelease.version} [skip ci]nn${nextRelease.notes}'