nodeLinker: pnp

npmAlwaysAuth: true
npmAuthToken: 5df75c13-1f84-4ed1-820b-8a4ec00db3bc

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

# packageExtensions:
#   "@jest/core@*":
#     peerDependencies:
#       ts-node: "*"
#     peerDependenciesMeta:
#       ts-node:
#         optional: true
#   jest-cli@*:
#     peerDependencies:
#       ts-node: "*"
#     peerDependenciesMeta:
#       "@types/node":
#         optional: true

yarnPath: .yarn/releases/yarn-3.2.0.cjs
