---
rules:
  '@typescript-eslint/brace-style':
    - 2
    - 1tbs
  '@typescript-eslint/no-shadow':
    - error
  '@typescript-eslint/no-use-before-define': 1
  align-assignments/align-assignments:
    - 2
    - requiresOnly: false
  align-import/align-import:
    - warn
  brace-style: 1
  curly: error
  camelcase:
    - warn
    - ignoreImports: true
  implicit-arrow-linebreak: off
  import/extensions: 0
  import/no-cycle: 1
  import/prefer-default-export: off
  json-files/sort-package-json: 1
  key-spacing:
    - error
    - align: value
      mode: strict
  lines-between-class-members:
    - error
    - always
  max-len:
    - 2
    - code: 120
      ignoreComments: true
      ignoreUrls: true
  no-underscore-dangle: off
  no-multi-spaces:
    - off
    - exceptions:
        ImportDeclaration: true
        Property: true
        VariableDeclarator: true
  no-shadow: 0
  no-use-before-define: 0
  no-param-reassign: warn
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      minKeys: 2
      natural: false
  sort-keys-fix/sort-keys-fix: warn
